import sys
import gzip


if len(sys.argv) != 3:
    print(f'Usage: python {sys.argv[0]} input.depth output_prefix')
    print('This script is used for converting depth file generated by `samtools depth` into the format compatible with `plot_depth.py`')
    sys.exit(1)


f_out = gzip.open(f'{sys.argv[-1]}.depth.gz', 'wb')
with open(sys.argv[1], 'r') as f:
    pre_chr_id = ''
    for line in f:
        chr_id, _, depth = line.strip().split('\t')
        if chr_id != pre_chr_id:
            f_out.write((f'>{chr_id}\n').encode('utf-8'))
            pre_chr_id = chr_id
        f_out.write((f'{depth}\n').encode('utf-8'))
f_out.close()
